# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 874c821e3d676c756c1eb04f9ac369756ce9f6e1ec2830cdbef7bbb0390cf9c5538c93155c67c7963c081bf293e7210110704016e35cf37f37e8d3aff27ace2d

test:
  secret_key_base: cef2301ac5821028f3575ac616f8fe18146386f2851af74995961398652f7e491e7e98c274e3c32d3f59dfee3f234063732a7a9a73e81338514b52bbc1fd6118

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
